# Generated by Django 3.2 on 2023-08-17 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_eleveM', models.CharField(max_length=50)),
                ('prenom_eleveM', models.CharField(max_length=50)),
                ('age_eleveM', models.PositiveIntegerField()),
                ('genre_eleveM', models.CharField(max_length=50, null=True)),
                ('num_tel_parentM', models.CharField(max_length=10, null=True, unique=False)),
                ('datenM', models.CharField(default='2010-01-01', max_length=100)),
            ],
        ),
    ]
