# Generated by Django 3.2 on 2023-08-19 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleve', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eleve',
            name='datenM',
        ),
        migrations.AddField(
            model_name='eleve',
            name='anneescol_eleveM',
            field=models.CharField(default='3eme annee', max_length=200),
        ),
        migrations.AddField(
            model_name='eleve',
            name='descr_eleveM',
            field=models.CharField(default='Anglais', max_length=200),
        ),
    ]
