# Generated by Django 3.2 on 2023-08-19 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleve', '0002_auto_20230819_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleve',
            name='anneescol_eleveM',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='descr_eleveM',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='num_tel_parentM',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
