# Generated by Django 3.2 on 2023-08-19 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleve', '0003_auto_20230819_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='eleve',
            name='frais_eleveM',
            field=models.CharField(default='non', max_length=10),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='num_tel_parentM',
            field=models.CharField(max_length=10),
        ),
    ]
