# Generated by Django 3.2 on 2023-08-19 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleve', '0004_auto_20230819_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleve',
            name='age_eleveM',
            field=models.PositiveIntegerField(default='00', null=True),
        ),
    ]
