# Generated by Django 3.2 on 2023-08-19 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleve', '0005_alter_eleve_age_elevem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleve',
            name='age_eleveM',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
