# Generated by Django 3.2 on 2023-08-22 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleve', '0006_alter_eleve_age_elevem'),
    ]

    operations = [
        migrations.CreateModel(
            name='EleveCEM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_eleveMCEM', models.CharField(max_length=50)),
                ('prenom_eleveMCEM', models.CharField(max_length=50)),
                ('age_eleveMCEM', models.PositiveIntegerField(null=True)),
                ('genre_eleveMCEM', models.CharField(max_length=50, null=True)),
                ('num_tel_parentMCEM', models.CharField(max_length=10)),
                ('anneescol_eleveMCEM', models.CharField(max_length=200)),
                ('descr_eleveMCEM', models.CharField(max_length=200)),
                ('nom_profMCEM', models.CharField(max_length=50)),
                ('frais_eleveMCEM', models.CharField(default='non', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ElevePre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_eleveMpre', models.CharField(max_length=50)),
                ('prenom_eleveMpre', models.CharField(max_length=50)),
                ('age_eleveMpre', models.PositiveIntegerField(null=True)),
                ('genre_eleveMpre', models.CharField(max_length=50, null=True)),
                ('num_tel_parentMpre', models.CharField(max_length=10)),
                ('anneescol_eleveMpre', models.CharField(max_length=200)),
                ('descr_eleveMpre', models.CharField(max_length=200)),
                ('nom_profMPre', models.CharField(max_length=50)),
                ('frais_eleveMpre', models.CharField(default='non', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ElevePrim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_eleveMPrim', models.CharField(max_length=50)),
                ('prenom_eleveMPrim', models.CharField(max_length=50)),
                ('age_eleveMPrim', models.PositiveIntegerField(null=True)),
                ('genre_eleveMPrim', models.CharField(max_length=50, null=True)),
                ('num_tel_parentMPrim', models.CharField(max_length=10)),
                ('anneescol_eleveMPrim', models.CharField(max_length=200)),
                ('descr_eleveMPrim', models.CharField(max_length=200)),
                ('nom_profPrim', models.CharField(max_length=50)),
                ('frais_eleveMPrim', models.CharField(default='non', max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='eleve',
            name='nom_prof',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
