# Generated by Django 3.2 on 2023-08-22 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eleve', '0007_auto_20230822_1836'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eleve',
            old_name='nom_prof',
            new_name='nom_profM',
        ),
        migrations.RenameField(
            model_name='eleveprim',
            old_name='nom_profPrim',
            new_name='nom_profMPrim',
        ),
    ]
