# Generated by Django 3.2 on 2023-09-01 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevedeux', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleve',
            name='frais_eleveM',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='elevecem',
            name='frais_eleveMCEM',
            field=models.CharField(default='non', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='elevepre',
            name='frais_eleveMpre',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='eleveprim',
            name='frais_eleveMPrim',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
